package com.npucraft.farmguard.model;

public enum RiskReason {
    EXCESSIVE_REDSTONE,
    EXCESSIVE_PISTONS,
    EXCESSIVE_HOPPERS,
    EXCESSIVE_ENTITIES,
    EXCESSIVE_ITEMS,
    EXCESSIVE_MINECARTS,
    EXCESSIVE_VILLAGERS,
    EXCESSIVE_SPAWNS,
    EXCESSIVE_BLOCK_UPDATES,
    RAPID_OSCILLATION,
    SUDDEN_SPIKE,
    SUSTAINED_LOAD,
    LAG_SUSPECT,
    STRONG_LAG_CORRELATION,
    RUNAWAY_GROWTH
}
